export const MENU_ACTIONS = {
  SHOW_MOBILE_NAVIGATION_MENU: "SHOW_MOBILE_NAVIGATION_MENU",
  HIDE_MOBILE_NAVIGATION_MENU: "HIDE_MOBILE_NAVIGATION_MENU",
};

export const USER_ACTIONS = {
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_NOT_LOGGED_IN: "USER_NOT_LOGGED_IN",
  SET_USER_ATTRIBUTES: "SET_USER_ATTRIBUTES",
};

export const CONNECTIONS_ACTIONS = {
  SET_CHART_FILTERS: "SET_CHART_FILTERS",
};
