import gql from "graphql-tag";

export default gql`
  query groupGetV2($id: ID!, $connectionId: ID) {
    groupGetV2(id: $id, connectionId: $connectionId) {
      id: ID
      name
      description
      createdAt
      updatedAt
      createdBy
      createdByUser{
        email
        given_name
        family_name
        company
      }

      members{
        email
        role
        joinedDate
        latestActivity
        user{
          email
          given_name
          family_name
          company
          }
      }

      pendingInvitations{
        invitedByUser{
          email
          given_name
          family_name
          company
        }
        createdAt
        email
      }

      settings{
        chat
        isPublic
        showUsers
        showScores:
        showSummaries
        addStartup
        addUser
        addEvaluation
      }

      evaluationTemplates{
        id
        createdAt
        updatedAt
        createdBy
        createdByUser{ 
          email
          given_name
          family_name
          company
        }
        name
        description
        sections{
          id
          createdAt
          updatedAt
          createdBy
          createdByUser{ 
            email
            given_name
            family_name
            company
          }
          name
          description
          questions{
            id
            createdBy
            createdByUser{
              email
              given_name
              family_name
              company
            }
            accountId
            createdAt
            updatedAt
            name
            description
            inputType
            options{
              val
              score
              index
              sid:
            }
          }
        }
      }

      startups{
        sharedByUser{ 
          email
          given_name
          family_name
          company
        }
        createdAt
        seen
        creative
        evaluations{
          id
          name
          description
          createdAt
          updatedAt
          createdBy
          createdByUser{
            email
            given_name
            family_name
            company
          }
          isMe
          templateId
          template {
            id
            createdAt
            updatedAt
            createdBy
            createdByUser{
              email
              given_name
              family_name
              company
            }
            name
            description
            sections{
              id
              createdAt
              updatedAt
              createdBy
              createdByUser{
                email
                given_name
                family_name
                company
              }
              name
              description
              questions{
                id
                createdBy
                createdByUser{
                  email
                  given_name
                  family_name
                  company
                }
                accountId
                createdAt
                updatedAt
                name
                description
                inputType
                options{
                  val
                  score
                  index
                  sid
                }
              }
            }
          }
          answers{
            id
            inputType
            questionId
            sectionId
            questionName
            sectionName
            sid
            val
          }
          summary{
            scoreTotal
            scorePossible
            scorePercent
            progressTotal
            progressPossible
            progressPercent
            templateId
            templateName
            sections{
              sectionId
              sectionName
              scoreTotal
              scorePossible
              scorePercent
              progressTotal
              progressPossible
              progressPercent
              scorePerAnswer{
                score
                possibleScore
                questionId
                questionName
              }
              }
            }
        }
        subjectiveScores{
          score
          createdBy
          createdAt
          isMe
          createdByUser{
            email
            given_name
            family_name
            company
          }
        }

        }
    }
  }
`;
