export const ICONPOSITION = { START: "START", END: "END", NONE: "NONE" };
export const OVERVIEWPAGESTATE = {
  OVERVIEW: "OVERVIEW",
  SHARETEMPLATE: "SHARETEMPLATE",
  ARCHIVElIST: "ARCHIVElIST",
};
export const REPORTCHARTS = {
  BAR: "BAR",
  COLUMN: "COLUMN",
  PIE: "PIE",
};

export const SETTINGSMENU = {
  HOME: "HOME",
  EVALUATIONTEMPLATE: "EVALUATIONTEMPLATE",
  TAGS: "TAGS",
  FUNNELS: "FUNNELS",
  YOURTEAM: "YOURTEAM",
  WEBFORM: "WEBFORM",
  USERPROFILE: "USERPROFILE",
  ACCOUNTSETTINGS: "ACCOUNTSETTINGS",
  NOTIFICATIONS: "NOTIFICATIONS",
};
