export const ICONPOSITION = { START: "START", END: "END", NONE: "NONE" };
export const OVERVIEWPAGESTATE = {
  OVERVIEW: "OVERVIEW",
  SHARETEMPLATE: "SHARETEMPLATE",
  ARCHIVElIST: "ARCHIVElIST",
};
